### ISSUE TITLE
I cannot use youtube-bot "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by Rurounius** [Logan1x/Python-Scripts#98]
This is my fault, i know but i don't know what to do. I just wrote the url and i took the "SyntaxError: invalid syntax" error message. Thanks for the scripts, but unfortunately i couldn't use.

```
import time
import webbrowser
import os

url = str(input("Enter your video url in ->\"https://www.youtube.com/watch?v=blabla\"<-  : "))
n = input("Enter refresh rate(seconds) : 70")
brow = input("Enter your default browser in ->\"Firefox ESR"<-  : ")
while (1):
    os.system(" killall -9 " + brow)
    time.sleep(int(n))
    webbrowser.open(url)
    print('Successfully Viewd')

```

Can u help me? What is my fault?

**Comment by Logan1x** [comment]
Can you show the terminal output for full error?

**Comment by Rurounius** [comment]
> Can you show the terminal output for full error?

ofc dear. it's here. sorry about that, i'm very noob. :))

![dot](https://user-images.githubusercontent.com/49091947/84956176-50637380-b101-11ea-9bfc-3bfc33c7680a.png)

**Comment by Logan1x** [comment]
Just remove that part, its just way of asking which browser you are using. Replace it by,

`brow = input("Enter your default browser  ")`

> i'm very noob

Not a problem, everyone is noob at beginning.

**Comment by Logan1x** [comment]
I tried to run the script and you might find problem in following lines,

`n = input("Enter refresh rate(seconds) : 70")`

This line is for how often you want to open new YouTube page. So when in terminal it asks for input give it a number(better if in range of 40 - 70) and then press enter.

`brow = input("Enter your default browser in ->\"Firefox ESR\"<-  : ")`

When your program run this line it will ask you for default browser, when you enter your browser name it may say `Firefox: no process found` or `Name_you_entered: no process found`. Don't worry program will still run, just wait for the time you entered in refresh rate and new tab in browser will open with YouTube link.

**Comment by Rurounius** [comment]
you are so kind Logan1x. I appriciate for your all second. everything is okay now but except one: does not increase view rate. browser opening, watching, waiting... but doesn't. sorry for bothering you friend.

**Comment by Logan1x** [comment]
> does not increase view rate.

It was bound to happen. YouTube has does some background checking. So if the request come from same IP, it count it as double and doesn't count it to view.

So I want you to run the script and then break it to you because you learn, error handling, how to make issues and even how to ask community. 

I am not sure that you will be able to increase your views on YouTube or not but I'll definitely teach you a lot(it was my motivation for programming). So stick to it and try more things. Like one thing you can do here is to check with changing IP every time you run this script.

Good luck for your future :)
